# Generated by Django 2.0.4 on 2018-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goodsAuthoe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
