# Generated by Django 2.0.4 on 2018-05-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0003_auto_20180516_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsName',
            field=models.CharField(max_length=100),
        ),
    ]
