# Generated by Django 2.0.4 on 2018-05-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0004_auto_20180516_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goodsAuthor',
        ),
    ]
