# Generated by Django 2.0.4 on 2018-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0005_remove_goods_goodsauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goodsDesc',
            field=models.CharField(max_length=800),
        ),
    ]
