# Generated by Django 2.0.4 on 2018-05-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddrInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aProvince', models.CharField(max_length=15)),
                ('aCity', models.CharField(max_length=15)),
                ('aDis', models.CharField(blank=True, max_length=15, null=True)),
                ('aAddressee', models.CharField(max_length=20)),
                ('aDetaAddr', models.CharField(max_length=30)),
                ('aPostCode', models.CharField(blank=True, max_length=10, null=True)),
                ('aPhoneNumber', models.CharField(max_length=15)),
                ('isDelete', models.BooleanField(default=False)),
                ('aDefaultAddr', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'addrinfo',
            },
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aTitle', models.CharField(max_length=20)),
                ('aParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.AreaInfo')),
            ],
            options={
                'db_table': 'areainfo',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('buyCount', models.IntegerField(default=1)),
                ('isDelete', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('goodsDesc', models.CharField(max_length=80)),
                ('goodsPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('goodsDetail', models.TextField()),
                ('imgPath', models.ImageField(upload_to='uploads/')),
                ('saleCount', models.IntegerField(default=0)),
                ('gPubdate', models.DateTimeField()),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('commentDate', models.DateTimeField()),
                ('comment', models.TextField()),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Goods')),
            ],
            options={
                'db_table': 'goodscomment',
            },
        ),
        migrations.CreateModel(
            name='GoodSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortName', models.CharField(max_length=10)),
                ('sortPic', models.ImageField(upload_to='uploads/')),
                ('sortClass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'goodsort',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('goodsPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('buyCount', models.IntegerField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Goods')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinish', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('orderTime', models.DateTimeField()),
                ('orderNumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='RecentSee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'recentsee',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=30)),
                ('uPassword', models.CharField(max_length=20)),
                ('uEmail', models.CharField(max_length=30)),
                ('uPhoneNumber', models.CharField(max_length=15, null=True)),
                ('uAddr', models.CharField(blank=True, max_length=50, null=True)),
                ('uRegDate', models.DateTimeField()),
                ('isDelete', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='recentsee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.UserInfo'),
        ),
        migrations.AddField(
            model_name='orders',
            name='userOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.UserInfo'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Orders'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goodSort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.GoodSort'),
        ),
        migrations.AddField(
            model_name='cart',
            name='userCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.UserInfo'),
        ),
        migrations.AddField(
            model_name='addrinfo',
            name='aUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.UserInfo'),
        ),
    ]
